config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'homes#top'
  get "home/about" => "homes#index"

  resources :users
  resources :homes
  resources :books do
    resources :favorites, only: [:create, :destroy]
  end
    resources :books, only: [:index, :show, :create] do
    resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
  belongs_to :user
  has_many :favorites
  has_many :favorites_users, through: :favorites, source: :user
  has_many :comments
end

app/models/book_commmment.rb
class BookCommmment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :book
  belongs_to :user
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image

  has_many :favorites, dependent: :destroy
  has_many :favorites_books, through: :favorites, source: :book

  has_many :comments

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


private
  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path  # ログアウト後に遷移するpathを設定
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
  	@books = Book.all
    @book = Book.new
    @user = current_user
    @favorite = Favorite.new
  end

  def show
  	@book = Book.find(params[:id])
    @newbook = Book.new
    @user = User.find(@book.user.id)
    @comments = @book.comments
    @comment = Comment.new
  end

  def new
  	@book = Book.new
  end

  def create
      @book = Book.new(book_params)
      @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render "index"
    end
  end

  def edit
  	 @book = Book.find(params[:id])
     @newbook = Book.new
     @user = User.find(@book.user_id)
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      flash[:notice] = "error."
      render action: :edit
    end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  	@favorite = current_user.likes.create(book_id: params[:book_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
  	@favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    @favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
  	@user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

    private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if flash[:notice] %>
　<div class="flash">
　<%= flash[:notice] %>
　</div>
<% end %>
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", class: "pull-left profile-thumb" %>
<table class="table">
    <tbody>
	    <tr>
	    	<th>name</th>
	    	<th><%= user.name %></th>
	    </tr>
	    <tr>
	    	<th>introduction</th>
	    	<th><%= user.introduction %></th>
	    </tr>
	</tbody>
</table>
<%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

<h3>New book</h3>
<%= form_for(book) do |f| %>
<% if book.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h3>
      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
	<h4>Title</h4>
	  <%= f.text_field :title, class: "col-xs-12" %>
	<h4>Opinion</h4>
	  <%= f.text_area :body, class: "col-xs-12" %>
	<%= f.submit 'Create Book', class: "col-xs-12 btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class='col-xs-9'>
      <% if flash[:notice] %>
      　<div class="flash">
        　<%= flash[:notice] %>
      　</div>
      <% end %>
      <h1>Editing Book</h1>
      <%= form_for(@book) do |f| %>
        <h4>Title</h4>
          <%= f.text_field :title %>
        <h4>Body</h4>
          <%= f.text_field :body %>
        <p><%= f.submit 'Update Book' %></p>
        <p><%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %></p>
      <% end %>

      <% if @book.errors.any? %>
          <div id="error_explanation">
            <h3><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h3>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
		<%= render 'books/list', book: @book, user: @user %>
		</div>
		<div class="col-xs-9">
			<h1>Books</h1>
			<table class='table table-hover table-inverse'>
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
				        <tr>
				        	<td>
					            <%= link_to user_path(book.user) do %>
					            <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", class: "pull-left profile-thumb" %>
				            <% end %>
				        	</td>
							<td><%= link_to book.title, book_path(book.id) %></td>
							<td><%= book.body %></td>
							<td>
								いいね件数: <%= @book.favorites.count %>
								<% if current_user.already_favorited?(@book) %>
									<%= button_to 'いいね削除', book_favorite_path(@book), method: :delete %>
								<% else %>
								<% end %>
							</td>

						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
    <%= render 'books/list', book: @newbook, user: @user %>
    </div>
    <div class='col-xs-9'>
    	<h2>Book detail</h2>
    	<table class='table'>
    	  <tr>
          <% if current_user == @user %>
            <td>
              <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", class: "pull-left profile-thumb" %>
              <% end %>
              <%= link_to @user.name, user_path(@user) %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
            <td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_id"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn-sm btn-danger destroy_book_id" %></td>
            <h3><%= @post.content %></h3>

            <h2>コメント一覧</h2>
            <% @comments.each do |c| %>
              <div>
                <a href="/users/<%= @book.user.id %>"><%= c.user.email %></a>
                <%= c.content %>
                <hr>
              </div>
            <% end %>

            <%= form_for [@post, @comment] do |f| %>
              <%= f.text_field :content %>
              <br>
              <%= f.submit 'コメントする' %>
          <% else %>
            <td>
              <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", class: "pull-left profile-thumb" %>
              <% end %>
              <%= link_to @user.name, user_path(@user) %>
            </td>
            <td><%= @book.title %></td>
            <td><%= @book.body %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/index.html.erb
<div class="container">
	<div class="body">
		<p id="notice"></p>
		<h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
	</div>
</div>

app/views/homes/top.html.erb
<div class="container">
<%= render 'layouts/logoutmessage' %>
	<h1>welcome to Bookers !!</h1>
	<p>In Bookers,</p>
	<p>you can share and exchange your opinions , inpressions , and emotions</p>
	<p>about various books!</p>


	<div class="btn-wrapper">
	  <div class="row">
	    <p><%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
	  </div>
	  <div class="row">
	    <p><%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
	  </div>
	</div>
</div>

app/views/layouts/_logoutmessage.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class='nav navbar-nav navbar-left' >
          <span class="bookers">Bookers</span>
        </nav>
        <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="">
              <%= link_to "Home", user_path(current_user.id) %>
            </li>
            <li class="">
              <%= link_to 'Users', users_path %>
            </li>
            <li class="">
              <%= link_to 'Books', books_path %>
            </li>
            <li class="">
              <%= link_to "logout", destroy_user_session_path, method: :delete %>
            </li>

          <% else %>
            <li class="">
              <%= link_to "Home", root_path %>
            </li>
            <li class="">
              <%= link_to "About", home_about_path %>
            </li>
            <li class="">
              <%= link_to "sign up", new_user_registration_path %>
            </li>
            <li class="">
              <%= link_to "login", new_user_session_path %>
            </li>
          <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <br>
    <br>
    <br>
    <%= yield %>
    <footer>
      <div class='container'>
        <div class='row'>
          <div class='col-xs-3 col-xs-offset-9'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
	<div class='row'>
		<div class='col-xs-3'>
			<h2>User info</h2>
		    	<%= form_for(@user) do |f| %>
			    	<h5>Name</h5>
			    		<%= f.text_field :name %>
					<h5>Image</h5>
						<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
					<h5>Introduction</h5>
						<%= f.text_field :introduction %>
						<%= f.submit "Update User", class: "btn btn-default" %>
				<% end %>
			<% if @user.errors.any? %>
				<div id="error_explanation">
					<h3><%= pluralize(@user.errors.count, "error") %> prohibited this book from being saved:</h3>
					<ul>
						<% @user.errors.full_messages.each do |message| %>
						<li><%= message %></li>
						<% end %>
					</ul>
				</div>
		    <% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
		<%= render 'books/list', book: @book, user: @user %>
		</div>
		<div class='col-xs-9'>
		<h1>Users</h1>
			<table class='table table-hover table-inverse'>
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
					</tr>
				</thead>
				<tbody>
					<% @users.each do |user| %>
				        <tr>
							<td><%= attachment_image_tag user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg", class: "pull-left profile-thumb" %></td>
							<td><%= user.name %></td>
							<td><%= link_to "Show", user_path(user.id) %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
    <%= render 'books/list', book: @book, user: @user %>
    </div>
    <div class='col-xs-9'>
    <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
            <tr>
          <% @books.each do |book| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", format: 'jpg', size: "30x30" %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>